USE [master]
GO
/****** Object:  Database [Cinema_db]    Script Date: 6/25/2020 6:05:59 PM ******/
CREATE DATABASE [Cinema_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Cinema_db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Cinema_db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Cinema_db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Cinema_db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Cinema_db] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Cinema_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Cinema_db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Cinema_db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Cinema_db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Cinema_db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Cinema_db] SET ARITHABORT OFF 
GO
ALTER DATABASE [Cinema_db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Cinema_db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Cinema_db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Cinema_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Cinema_db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Cinema_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Cinema_db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Cinema_db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Cinema_db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Cinema_db] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Cinema_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Cinema_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Cinema_db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Cinema_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Cinema_db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Cinema_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Cinema_db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Cinema_db] SET RECOVERY FULL 
GO
ALTER DATABASE [Cinema_db] SET  MULTI_USER 
GO
ALTER DATABASE [Cinema_db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Cinema_db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Cinema_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Cinema_db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Cinema_db] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Cinema_db', N'ON'
GO
ALTER DATABASE [Cinema_db] SET QUERY_STORE = OFF
GO
USE [Cinema_db]
GO
/****** Object:  Table [dbo].[Films]    Script Date: 6/25/2020 6:05:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Films](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[title] [nvarchar](100) NULL,
	[year] [int] NULL,
	[time] [int] NULL,
	[age] [int] NULL,
	[rating] [float] NULL,
	[trailer] [nvarchar](255) NULL,
 CONSTRAINT [PK_Films_1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 6/25/2020 6:05:59 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NULL,
	[password] [nvarchar](50) NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Cinema_db] SET  READ_WRITE 
GO
